# Generated by Django 3.2.6 on 2021-09-02 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_auto_20210827_0818"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="permitted_users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
